### PR TITLE
Apply `cargo fmt` to all source code

### PR DESCRIPTION
**Pull request by romanz**
Also, make sure that Travis runs `cargo fmt` check on every build.

### CODE REVIEW

**Comment by romanz** [comment]
NOTE: this PR depends on #13.

**Comment by romanz** [comment]
This PR probably conflicts with #8 - can be postponed after #8 is merged.

**Comment by gbenattar** [comment]
This is really really cool!

**Comment by romanz** [comment]
Thanks :)
I'm afraid that the merge was done to `travis` branch, and not to `master` - I'll re-open the PR.

**Pull request merged**
